import nodemailer from "nodemailer";
import { asyncHandler } from "../utils/asyncHandler.js";

const sendEmail = asyncHandler(async (to, subject, html) => {
    try {
        console.log("sendEmail: Starting email send");
        console.log("sendEmail: To:", to);
        console.log("sendEmail: Subject:", subject);
        console.log("sendEmail: Gmail User:", process.env.GMAIL_USER);
        console.log("sendEmail: Gmail Pass exists:", !!process.env.GMAIL_APP_PASSWORD);

        const transporter = nodemailer.createTransport(
            {
                service: "gmail",
                auth: {
                    user: process.env.GMAIL_USER,
                    pass: process.env.GMAIL_APP_PASSWORD //differnet password that generated by gmail
                }
            }
        );

        console.log("sendEmail: Transporter created, attempting to send...");

        const result = await transporter.sendMail(
            {
                from: `"FindMySquare" <${process.env.GMAIL_USER}>`,
                to,
                subject,
                html,
            }
        );

        console.log("sendEmail: Email sent successfully. Response:", result.response);
        return result;
    } catch (error) {
        console.error("sendEmail: Error occurred:", error);
        throw error;
    }
});

export {sendEmail};