import nodemailer from "nodemailer";
import { asyncHandler } from "../utils/asyncHandler.js";

const sendEmail = asyncHandler(async (to, subject, html) => {

    const transporter = nodemailer.createTransport(
        {
            service: "gmail",
            auth: {
                user: process.env.GMAIL_USER,
                pass: process.env.GMAIL_APP_PASSWORD //differnet password that generated by gmail
            }
        }
    );

    await transporter.sendMail(
        {
            from: `"Your App" <${process.env.GMAIL_USER}>`,
            to,
            subject,
            html,
        }
    );
});

export {sendEmail};